# Generated by Django 5.1.6 on 2025-03-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_student_teacheer_profilepermission_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacheer_ProfilePermission',
            new_name='Teacher_ProfilePermission',
        ),
    ]
