# Generated by Django 5.1.6 on 2025-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_teacheer_profilepermission_teacher_profilepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Media/icons')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
