# Generated by Django 5.1.6 on 2025-04-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
