# Generated by Django 5.1.6 on 2025-04-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(null=True, upload_to='Media/featured_img')),
                ('featured_video', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('deadline', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                ('Certificate', models.CharField(max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.instructor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.categories')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.language')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.level')),
            ],
        ),
    ]
