# Generated by Django 5.1.6 on 2025-04-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_videomodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
