# Generated by Django 5.1.6 on 2025-04-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_teacher_profilepermission_create_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teacher.lesson'),
        ),
    ]
