# Generated by Django 5.1.6 on 2025-04-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_alter_videomodels_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.lesson'),
        ),
    ]
