# Generated by Django 5.1.6 on 2025-05-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_payment_user_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
