# Generated by Django 5.1.6 on 2025-05-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_is_superadmin_account_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superuser',
            new_name='is_superadmin',
        ),
    ]
