# Generated by Django 5.2.1 on 2025-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_account_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=20),
        ),
    ]
