# Generated by Django 5.1.6 on 2025-03-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profilepermission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_ProfilePermission',
        ),
    ]
