# Generated by Django 5.1.6 on 2025-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriestheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='default_value_here', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
