# Generated by Django 5.1.6 on 2025-04-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
