# Generated by Django 5.1.6 on 2025-03-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_profilepermission',
            old_name='student',
            new_name='guest',
        ),
    ]
