# Generated by Django 5.2.1 on 2025-06-06 10:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_rename_student_guest_profilepermission_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Media/icons')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_CourseResource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_Requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_VideoModels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_What_u_learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='create_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_CourseResource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_Requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_VideoModels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_What_u_learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='delete_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_CourseResource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_Requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_VideoModels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_What_u_learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='edit_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_CourseResource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_Requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_VideoModels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_What_u_learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest_profilepermission',
            name='manage_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(null=True, upload_to='Media/featured_img')),
                ('featured_video', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('deadline', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                ('Certificate', models.CharField(max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.categories')),
            ],
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Note', 'Note'), ('PDF', 'PDF'), ('PPT', 'PPT')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(default='path/to/default/file.pdf', upload_to='course_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('about_author', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_instructors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.language'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.levels'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='guest.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='guest.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('score_percentage', models.FloatField(blank=True, null=True)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('verified', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_uploaded_certificates', to=settings.AUTH_USER_MODEL)),
                ('quiz_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='guest.quizresult')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='Media/Yt_Thumbnail')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('time_duration', models.IntegerField(null=True)),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='Media/Yt_Thumbnail')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('time_duration', models.IntegerField(null=True)),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='What_u_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
    ]
